# Generated by Django 3.2.9 on 2021-12-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_cake_sandwich'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colddrinks',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
