# Generated by Django 3.2.9 on 2021-12-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_colddrinks_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colddrinks',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
