# Generated by Django 3.2.9 on 2021-12-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_colddrinks_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=200), max_length=200),
        ),
        migrations.AddField(
            model_name='colddrinks',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=200), max_length=200),
        ),
        migrations.AddField(
            model_name='hotdrinks',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=200), max_length=200),
        ),
        migrations.AddField(
            model_name='sandwich',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=200), max_length=200),
        ),
    ]
