# Generated by Django 3.2.9 on 2022-01-06 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0008_menu_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotdrinks',
            name='likes',
            field=models.ManyToManyField(related_name='menu_item', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cake',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
        migrations.AlterField(
            model_name='colddrinks',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
        migrations.AlterField(
            model_name='hotdrinks',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
