# Generated by Django 3.2.9 on 2022-01-06 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0009_auto_20220106_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='likes',
            field=models.ManyToManyField(related_name='cake_item', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='colddrinks',
            name='likes',
            field=models.ManyToManyField(related_name='cold_drink_item', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sandwich',
            name='likes',
            field=models.ManyToManyField(related_name='sandwich_item', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hotdrinks',
            name='likes',
            field=models.ManyToManyField(related_name='hot_drink_item', to=settings.AUTH_USER_MODEL),
        ),
    ]
