# Generated by Django 3.2.9 on 2021-12-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.CharField(choices=[('10am', '10am'), ('12am', '12am'), ('2pm', '2pm'), ('4pm', '4pm')], default='4pm', max_length=100),
        ),
    ]
