# Generated by Django 3.2.9 on 2022-01-24 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20220112_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['datetime']},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='information',
            field=models.TextField(default='Please enter number of people:'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid number in the format: 07999999999', regex='^(07)\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.CharField(choices=[('9', '9am'), ('10', '10am'), ('11', '11am'), ('12', '12pm'), ('1', '1pm'), ('2', '2pm'), ('3', '3pm'), ('4', '4pm')], default='9', max_length=100),
        ),
    ]
